### PR TITLE
Provenance DAG bug tracker integration

### LINKED ISSUE #22: Have the Provenance DAG alert users to bugs with the versions of the plugins they are using
This will involve the creation of a database that tracks the known issues with different versions of QIIME 2 plugins/dependencies/etc.

This database will be queried by the prov parser in view. If serious issues are found we will create a pop-up alert to the user about them (say the OpenBLAS AVX512 debacle).

Query results will need to be viewable in some way and the user will need to be alerted to the fact that this query happened and finished with either:

1. Error unable to complete query (probably no internet connection)
2. No issues found
3. X issues of Y severity found

### PR DESCRIPTION
**Pull request by Oddant1**
closes #22

### CODE REVIEW

File: src/lib/models/readerModel.ts [hunk 1]
```diff
@@ -297,8 +307,36 @@ class ReaderModel {
 
     // Set Provenance
     loading.setMessage("Loading Provenance");
+    // Only read the errors from yaml the first time they drop in a result
+    if (!this.errors_read) {
```
Comment (colinvwood) [inline src/lib/models/readerModel.ts]:
```suggestion
    if ([this.LOW_SEVERITY_ERRORS, this.MEDIUM_SEVERITY_ERRORS, this.HIGH_SEVERITY_ERRORS].every(e => e === undefined)) {
```

Comment (colinvwood) [reply src/lib/models/readerModel.ts]: and then no `errors_read`

File: src/lib/models/readerModel.ts [hunk 2]
```diff
@@ -297,8 +307,36 @@ class ReaderModel {
...
+    await this.provenanceModel.getErrors(this.MEDIUM_SEVERITY_ERRORS, 1);
+    await this.provenanceModel.getErrors(this.HIGH_SEVERITY_ERRORS, 2);
+  }
+
+  async _readErrors() {
+    this.LOW_SEVERITY_ERRORS = yaml.safeLoad(
+      await readBlobAsText(
+        await (await fetch("/errors/LowSeverityErrors.yml")).blob(),
+      ),
+    ) as ProvenanceError[];
```
Comment (colinvwood) [inline src/lib/models/readerModel.ts:326]: worth making a func?

File: src/lib/models/provenanceModel.ts [hunk 3]
```diff
@@ -36,21 +47,25 @@ export default class ProvenanceModel {
...
 
   searchError: any = null;
+
+  // Metadata
   seenMetadata: Set<string> = new Set();
   metadata: Array<Array<string>> = [];
 
+  // Error tracking
+  nodeIDToErrors: Map<string, Map<number, ProvenanceError[]>> = new Map();
+  errors: Map<number, ProvenanceError[]> = new Map();
```
Comment (colinvwood) [inline src/lib/models/provenanceModel.ts:67]: might be a bit more readable if keys were strings ("low", "medium", "high")

File: src/lib/components/ErrorWarningModal.svelte [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+    >
+    </div>
+    <div
+      class="fixed left-1/2 top-1/2 z-50 max-h-[85vh] w-[90vw]
+            max-w-[510px] -translate-x-1/2 -translate-y-1/2 rounded-lg bg-white
+            p-4 shadow-lg border border-gray-200"
+      use:melt={$content}
+    >
+      <h2 use:melt={$title} class="text-lg">
+        {#if readerModel.provenanceModel.errors.get(2)?.length === 1}
```
Comment (colinvwood) [inline src/lib/components/ErrorWarningModal.svelte]:
```suggestion
        {#if readerModel.provenanceModel.errors.get(2)!.length === 1}
```

File: src/lib/models/provenanceModel.ts (hunk 3 above)
Comment (Oddant1) [reply src/lib/models/provenanceModel.ts:67]: I left the numbers to make it easier to add more categories in the future. We also actually renamed low to notes, medium to warnings, and high to errors in the actual UI

File: src/lib/models/readerModel.ts (hunk 2 above)
Comment (Oddant1) [reply src/lib/models/readerModel.ts:326]: Maybe? I was on the fence about that
